### ISSUE TITLE
Problem start wallet

### ISSUE THREAD

**Issue by TymekMM** [vidulum/DesktopWallet#1]
Wallet starting and downloading keys. 
When all keys are downloaded I have error message.
I am trying to us it on windows 2016 Standard and on windows 2019 Datacenter.
In both systems it not working.

Error: https://cdn.discordapp.com/attachments/456266103484841991/612939533608026133/unknown.png

**Comment by Corey-Code** [comment]
https://github.com/vidulum/DesktopWallet/commit/3ca323c3473d55cc694e364c085365a2a197e30e

please try nightly

https://github.com/vidulum/DesktopWallet/releases/download/v2.0.1/Vidulum.Setup.2.0.1_1-Nightly-Win.zip

**Comment by TymekMM** [comment]
This update does not fix my problem. Wallet can't take old data from the folder. Only clean installation is possible for me on all 10 windows 2016 and 2019 servers.

**Comment by TymekMM** [comment]
To reproduce problem with starting just add empty lines to the end of file masternode.conf or vidulum.conf

**Comment by Corey-Code** [comment]
Problem resolved by removing empty lines from users config files.

**Comment by TymekMM** [comment]
I think that it is not correct solution for the problem. 
It should be proper code behind to skip empty lines in .the configs.
