### ISSUE TITLE
Page Transactions

### ISSUE THREAD

**Issue by TymekMM** [vidulum/DesktopWallet#13]
It is not visible that last transaction is not confirmed yet.
Also missing info how many of 5 confirmations already are.
To get info you have to click on the transaction.

**Comment by Corey-Code** [comment]
"To get info you have to click on the transaction." You solved this one yourself.

**Comment by TymekMM** [comment]
This is not how it should be, on every error is the solution to go around but it should be implemented.
If you will make 10 transaction you will have to click each of them to see if it is already done.
It should be visible information at the list itself.
