### ISSUE TITLE
MasterNode stop working after 12h

### ISSUE THREAD

**Issue by TymekMM** [vidulum/DesktopWallet#17]
I did install new wallet. It was working and receiving rewards.
Stop working after 12h and this error after trying to start:
![New wallet MN problem after 12h](https://user-images.githubusercontent.com/33421309/63647443-e87f0f00-c721-11e9-9549-3ba9c77dff60.png)

Old wallet which was working without any problems months now on same data folder error:
![MN old wallet same data folder](https://user-images.githubusercontent.com/33421309/63647460-1401f980-c722-11e9-8e08-c7cf3c27ec4c.JPG)
Now same error in old wallet:
![Old wallet start mn error](https://user-images.githubusercontent.com/33421309/63647516-912d6e80-c722-11e9-8ced-4bc73e76d6ff.JPG)

Looks like new wallet clear old transactions from the history.

**Comment by TymekMM** [comment]
In the past MasterNode could work without 15K on the wallet, only proper TXT was needed.
And this was same for new wallet. I could start MasterNodes like in the past.
It was started and it does receive rewards. After 12h it stops with errors above.
To start MN again I have to import account with 15K where was initial transfer.

**Comment by Corey-Code** [comment]
Is this resolved?

**Comment by Corey-Code** [comment]
Again for the fifth time on your issues reported TymekMM - no response. Closing issue.
