### ISSUE TITLE
Problem with refresh total amount in the wallet after import key

### ISSUE THREAD

**Issue by TymekMM** [vidulum/DesktopWallet#18]
After importing new key to the wallet total amount not updated.
Transactions in the history are but total amount is ZERO
![Total amount not uptdated after import key](https://user-images.githubusercontent.com/33421309/63647737-f3d43980-c725-11e9-9cbc-37fb7b68b900.JPG)

**Comment by Corey-Code** [comment]
Are you still having this issue?

**Comment by Corey-Code** [comment]
Tested in 2.0.5 to be working. No response still - closing issue.
