### ISSUE TITLE
Starting Masternode is just giving starting masternodes with Vidulum.Setup.2.0.1_2-Nightly-Win

### ISSUE THREAD

**Issue by gucky25** [vidulum/DesktopWallet#22]
Because I'm also having issues with screens and scrolling inside the Vidulum Desktop Wallet I installed the 2.0.1_2 Nightly build.

Installing went okay, but after when the software start and I try to Start Maternode I'm just getting a black screen with a running circle, Staring masternode... and this will not stop.

Can I do something to solve this? Maybe delete old installation and install clean, because I did an upgrade of the Wallet software.

This wallet is running on:
- Windows Server 2016
- With 8 GB RAM
- With Intel Xeon Gold 6140 2.30 GHz processor

**Comment by gucky25** [comment]
Or is a masternode allways started by defeault and I do not have to start it manually?

**Comment by Corey-Code** [comment]
> Or is a masternode allways started by defeault and I do not have to start it manually?

Sorry for a delayed response here. Please download latest release (2.0.4) and let me know if you are still having an issue.

**Comment by Corey-Code** [comment]
2.0.5 confirmed resolves this issue.
