### ISSUE TITLE
Dashboard page - missing scrollbar 

### ISSUE THREAD

**Issue by TymekMM** [vidulum/DesktopWallet#6]
Dashboard page doesn't have scroll bar and it is not possible to scroll list of last transactions with mouse without scroll wheel.
You can scroll this list only when you click on any last transaction and when detail info is at front you can use arrow keys. When detail info about transaction is closed no more scroll possibilities.

**Comment by Corey-Code** [comment]
I am unable to recreate this issue. Scrolling works on both the dashboard and the transactions list. Please provide system details
