### ISSUE TITLE
Page Transactions date missing

### ISSUE THREAD

**Issue by TymekMM** [vidulum/DesktopWallet#7]
There is only time of transaction without DATE ! If you have transactions over several days to know which day it was you have to click on transaction

**Comment by Corey-Code** [comment]
![image](https://user-images.githubusercontent.com/37006206/63655867-598ee880-c75b-11e9-9443-4fd0f160de07.png)

Date is provided in the header of each list of transactions

**Comment by TymekMM** [comment]
If you will have 100 transactions you will be lost which date they are during scrolling.
Especially when you will use page down or page up keys it can be that gap with date can be missed by user. I had this many times during scroll my transactions.
Date should be with transaction itself.
